from skills.base import ChimeraSkill
from pydantic import BaseModel
from typing import Dict, Any


class ContentCreatorInput(BaseModel):
    trend_data: Dict[str, Any]
    platform: str
    voice_ref: str


class ContentCreatorOutput(BaseModel):
    text_content: str
    media_prompt: str
    confidence_score: float


class ContentCreatorSkill(ChimeraSkill):
    @property
    def name(self) -> str:
        return "skill_content_creator"

    async def execute(self, input_data: ContentCreatorInput) -> ContentCreatorOutput:
        """Minimal content creator stub that formats a short post using trend_data.

        This returns deterministic, test-friendly content for the TDD harness.
        """
        trend_summary = ""
        if isinstance(input_data.trend_data, dict) and input_data.trend_data:
            # summarize keys
            trend_summary = ", ".join(list(input_data.trend_data.keys())[:3])
        else:
            trend_summary = "no trends"

        text = f"[{input_data.platform}] {trend_summary} — generated by Chimera"
        media_prompt = f"Create an image that represents: {trend_summary}"
        return ContentCreatorOutput(text_content=text, media_prompt=media_prompt, confidence_score=0.8)
